### ISSUE TITLE
Investigate strenthening association between Harvest Source and XML file granule in WAF

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-harvesting#35]
Placeholder issue to investigate whether it's possible to maintain an association between a harvest source and individual XML files harvested into an Organization central WAF. 

This would allow immediate removal of XML files from a deleted harvest source in the centralized WAF, and a subsequent CKAN harvest for immediate(ish) feedback.

**Comment by lukecampbell** [comment]
Context: We want the ability to have a provider be able to delete a record and have the deletion propagate through the catalog immediately after a harvest.
